"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['/Users/virt1/Documents/repos/StagingUtility/nsp_staging_utility/guiapp.py']
DATA_FILES = []
OPTIONS = {'bdist_base': '/Users/virt1/Documents/repos/StagingUtility/Py2App_Files/build',
 'dist_dir': '/Users/virt1/Documents/repos/StagingUtility/Py2App_Files/dist'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
